prefetch_on_hover = true

[filters]
shelves = []

[[filters.saved]]
name = "harmless screenshot"
active_group = []

[filters.saved.tree.root]
kind = "group"

[filters.saved.tree.root.group]
op = "and"

[[filters.saved.tree.root.group.children]]
kind = "atom"

[filters.saved.tree.root.group.children.atom]
kind = "rating"
value = "general"
