#!/bin/sh
set -eu

root=$(CDPATH='' cd -- "$(dirname -- "$0")/.." && pwd)
cd "$root"

cargo package --workspace --locked \
    --exclude abv-acceptance \
    --exclude abv-portability \
    --exclude xtask
